/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfacegraphiques;

import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author marwa
 */
public class MiniGame extends javax.swing.JFrame {
        private int scoreU=0;
        private int scoreC=0;
        private int choixUser, choixCmpt;
        Random rand = new Random();
    /**
     * Creates new form cours12
     */
    public MiniGame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cours131 = new interfacegraphiques.cours13();
        ImgCmpt = new javax.swing.JLabel();
        ImgUser = new javax.swing.JLabel();
        ScoreUser = new javax.swing.JLabel();
        ScoreCmpt = new javax.swing.JLabel();
        ResultTxt = new javax.swing.JLabel();
        PierreBtn = new javax.swing.JButton();
        PapierBtn = new javax.swing.JButton();
        CiseauxBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(432, 509));
        setMinimumSize(new java.awt.Dimension(432, 509));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ImgCmpt.setBackground(new java.awt.Color(255, 255, 255));
        ImgCmpt.setOpaque(true);
        getContentPane().add(ImgCmpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 91, 89));

        ImgUser.setBackground(new java.awt.Color(255, 255, 255));
        ImgUser.setOpaque(true);
        getContentPane().add(ImgUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 91, 89));

        ScoreUser.setBackground(new java.awt.Color(51, 51, 255));
        ScoreUser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ScoreUser.setForeground(new java.awt.Color(255, 255, 255));
        ScoreUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScoreUser.setText("-");
        ScoreUser.setOpaque(true);
        getContentPane().add(ScoreUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 66, -1));

        ScoreCmpt.setBackground(new java.awt.Color(255, 102, 0));
        ScoreCmpt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ScoreCmpt.setForeground(new java.awt.Color(255, 255, 255));
        ScoreCmpt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ScoreCmpt.setText("-");
        ScoreCmpt.setOpaque(true);
        getContentPane().add(ScoreCmpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 66, -1));

        ResultTxt.setBackground(new java.awt.Color(255, 255, 255));
        ResultTxt.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        ResultTxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ResultTxt.setOpaque(true);
        getContentPane().add(ResultTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 310, 35));

        PierreBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        PierreBtn.setText("Rock");
        PierreBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PierreBtn.setContentAreaFilled(false);
        PierreBtn.setFocusPainted(false);
        PierreBtn.setFocusable(false);
        PierreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PierreBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PierreBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 308, 107, 33));

        PapierBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        PapierBtn.setText("Paper");
        PapierBtn.setToolTipText("");
        PapierBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        PapierBtn.setContentAreaFilled(false);
        PapierBtn.setFocusPainted(false);
        PapierBtn.setFocusable(false);
        PapierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PapierBtnActionPerformed(evt);
            }
        });
        getContentPane().add(PapierBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 353, 107, 33));

        CiseauxBtn.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        CiseauxBtn.setText("Scissors ");
        CiseauxBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        CiseauxBtn.setContentAreaFilled(false);
        CiseauxBtn.setFocusPainted(false);
        CiseauxBtn.setFocusable(false);
        CiseauxBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CiseauxBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CiseauxBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 404, 107, 33));

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 102, 0));
        jLabel1.setText("Computer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("You");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void choixCmpt(){
        choixCmpt= rand.nextInt(3); //choose number from 0 to 3 and 3 is not included
            switch (choixCmpt) {
                case 0:
                    ImgCmpt.setIcon(new ImageIcon("src//Images//pierre.png"));
                    break;
                case 1:
                    ImgCmpt.setIcon(new ImageIcon("src//Images//papier.png"));
                    break;
                default:
                    ImgCmpt.setIcon(new ImageIcon("src//Images//ciseaux.png"));
                    break;
            }
    }

    private void win(){
           if((choixUser==0 && choixCmpt==0) || (choixUser==1 && choixCmpt==1) || (choixUser==2 && choixCmpt==2)){
            ResultTxt.setText("you are equal");
            ScoreCmpt.setText(String.valueOf(scoreC));
            ScoreUser.setText(String.valueOf(scoreU));
           }
           else if((choixUser==0 && choixCmpt==1) || (choixUser==1 && choixCmpt==2) || (choixUser==2 && choixCmpt==0)){
             ResultTxt.setText("you loose");
             scoreC++;
             ScoreCmpt.setText(String.valueOf(scoreC));
             ScoreUser.setText(String.valueOf(scoreU));
           }
           else{
               ResultTxt.setText("you win");
               scoreU++;
               ScoreCmpt.setText(String.valueOf(scoreC));
               ScoreUser.setText(String.valueOf(scoreU));
           }
           
    }
        private void GameOver(){
        if(scoreU == 3 ){
           int continueGame= JOptionPane.showConfirmDialog(this, "You Win! Retry ", "Game Over", JOptionPane.YES_NO_OPTION);
           if(continueGame==1){
               System.exit(0);
           }
           else{
               scoreC=0;
               scoreU=0; 
               ScoreCmpt.setText(String.valueOf(scoreC));
               ScoreUser.setText(String.valueOf(scoreU));
               ResultTxt.setText("");
               ImgUser.setIcon(new ImageIcon(""));
               ImgCmpt.setIcon(new ImageIcon(""));
           } 
        }
        
        if(scoreC == 3 ){
           int continueGame= JOptionPane.showConfirmDialog(this, "You Loose! Retry ", "Game Over", JOptionPane.YES_NO_OPTION);
           if(continueGame==1){
               System.exit(0);
           }
           else{
               scoreC=0;
               scoreU=0; 
               ScoreCmpt.setText(String.valueOf(scoreC));
               ScoreUser.setText(String.valueOf(scoreU));
               ResultTxt.setText("");
               ImgUser.setIcon(new ImageIcon(""));
               ImgCmpt.setIcon(new ImageIcon(""));
           } 
        }
    }
    private void PierreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PierreBtnActionPerformed
        // TODO add your handling code here:
        choixUser=0;
        ImgUser.setIcon(new ImageIcon("src//Images//pierre.png"));
        choixCmpt();
        win();
        GameOver();
    }//GEN-LAST:event_PierreBtnActionPerformed

    private void PapierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PapierBtnActionPerformed
        // TODO add your handling code here:
        choixUser=1;
        ImgUser.setIcon(new ImageIcon("src//Images//papier.png"));
        choixCmpt();
        win();
        GameOver();
    }//GEN-LAST:event_PapierBtnActionPerformed

    private void CiseauxBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CiseauxBtnActionPerformed
        // TODO add your handling code here:
        choixUser=2;
        ImgUser.setIcon(new ImageIcon("src//Images//ciseaux.png"));
        choixCmpt();
        win();
        GameOver();
    }//GEN-LAST:event_CiseauxBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiniGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiniGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiniGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiniGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiniGame().setVisible(true);
                new MiniGame().setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CiseauxBtn;
    private javax.swing.JLabel ImgCmpt;
    private javax.swing.JLabel ImgUser;
    private javax.swing.JButton PapierBtn;
    private javax.swing.JButton PierreBtn;
    private javax.swing.JLabel ResultTxt;
    private javax.swing.JLabel ScoreCmpt;
    private javax.swing.JLabel ScoreUser;
    private interfacegraphiques.cours13 cours131;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
